Adds a new user method invalidate_remembered_browsers
auth0/auth0-python pull request #248
Opened 2020-11-25 23:00 UTC by kpurdon

### Changes

Please describe both what is changing and why this is important. Include:

- Adds a missing endpoint to invalidate all remembered browsers (mfa) for a user

### References

https://auth0.com/docs/api/management/v2#!/Users/post_invalidate_remember_browser

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

- [ ] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [ ] All existing and new tests complete without errors

2020-12-02 20:33 UTC, kpurdon commented
@lbalmaceda from issues it looks like your the correct person to check in with on this (LMK if that's not the case). Anything I can do to get this reviewed? Thanks!

2020-12-22 16:35 UTC, lbalmaceda requested changes
Looks good. Just one minor request around the value used as input in the tests.

2020-12-22 16:35 UTC, lbalmaceda commented on auth0/v3/test/management/test_users.py
> +        u.invalidate_remembered_browsers('used_id')
```suggestion
        u.invalidate_remembered_browsers('user-id')
```

2020-12-22 16:35 UTC, lbalmaceda commented on auth0/v3/test/management/test_users.py
> +        self.assertEqual('https://domain/api/v2/users/used_id/multifactor/actions/invalidate-remember-browser', args[0])
```suggestion
        self.assertEqual('https://domain/api/v2/users/user-id/multifactor/actions/invalidate-remember-browser', args[0])
```

2020-12-22 16:41 UTC, lbalmaceda approved these changes

2020-12-22 16:41 UTC, merged