Add scope to refresh_token
auth0/auth0-python pull request #256
Opened 2021-03-08 21:21 UTC by criles25

### Changes

Adding `scope` param to `refresh_token`.

### References

The auth0 API supports the `scope` param when refreshing token.

### Testing

- [x] This change adds unit test coverage

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors

2021-03-10 16:27 UTC, lbalmaceda requested changes
Thanks, the addition is correct 👍 left a comment

2021-03-10 16:27 UTC, lbalmaceda commented on auth0/v3/authentication/get_token.py
> +    def refresh_token(self, client_id, client_secret, refresh_token, scope,
I believe this will be a breaking change for those calling it without named arguments. We should place the new value on the last place.

2021-03-10 17:06 UTC, criles25 commented
the empty string default `scope=''` behaves the same as it being left out when calling the auth0 API

```
# scope=""
charlesriley@Charless-MBP auth0-python % curl --request POST \                                                                    
--url 'https://xometry-monolith-development.us.auth0.com/oauth/token' \
--header 'content-type: application/x-www-form-urlencoded' \
--data 'grant_type=refresh_token&client_id=foo&client_secret=bar&scope=""&refresh_token=baz'
{"access_token":"JWT","scope":"offline_access","expires_in":86400,"token_type":"Bearer"}%                                                                 

# scope left out 
charlesriley@Charless-MBP auth0-python % curl --request POST \                                                                    
--url 'https://xometry-monolith-development.us.auth0.com/oauth/token' \
--header 'content-type: application/x-www-form-urlencoded' \
--data 'grant_type=refresh_token&client_id=foo&client_secret=bar&refresh_token=baz' 
{"access_token":"JWT","scope":"offline_access","expires_in":86400,"token_type":"Bearer"}%                                                                 
```

2021-03-29 11:16 UTC, lbalmaceda approved these changes

2021-03-29 11:20 UTC, merged