Use requests session instead of requests
auth0/auth0-python pull request #344
Opened 2022-06-07 19:39 UTC by ozooxo

### Changes

As mentioned in https://requests.readthedocs.io/en/latest/user/advanced/#session-objects if all the calls are to the same host, we should use session objects for better performance. We also get the chance to customize connection pool as well.

> So if you’re making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see [HTTP persistent connection](https://en.wikipedia.org/wiki/HTTP_persistent_connection)).

Here I just setup `pool_connection=10, pool_maxsize=10`, which is the default of https://requests.readthedocs.io/en/master/api/#requests.adapters.HTTPAdapter

### References

Please include relevant links supporting this change such as a:

- support ticket
- community post
  - https://laike9m.com/blog/requests-secret-pool_connections-and-pool_maxsize,89/
- StackOverflow post
  - https://stackoverflow.com/questions/18466079/change-the-connection-pool-size-for-pythons-requests-module-when-in-threading
- support forum thread

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

- [ ] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [ ] All existing and new tests complete without errors

2022-06-07 19:40 UTC, ozooxo commented on auth0/v3/rest.py
> +        self.session.headers.update(self.base_headers)
> Sessions can also be used to provide default data to the request methods. 
> Any dictionaries that you pass to a request method will be merged with the session-level values that are set. The method-level parameters override session parameters.

2022-06-14 08:52 UTC, adamjmcgrath requested changes
Thanks for your contribution @ozooxo - couple of changes requested

2022-06-14 08:52 UTC, adamjmcgrath commented on auth0/v3/rest.py
> +        print("1111111")
You've left some debugging statements in here

2022-06-14 08:52 UTC, adamjmcgrath commented on auth0/v3/rest.py
> +    def __init__(self, jwt, telemetry=True, timeout=5.0, options=None, pool_connection=10, pool_maxsize=10):
You need to add `pool_connections` and `pool_maxsize` to `RestClientOptions` and then access them through the `options` kwarg. (this should fix the tests as well)

And, can you normalise the name of this to `pool_connections` everywhere

2022-07-29 11:41 UTC, adamjmcgrath commented
Closing due to inactivity - feel free to ping me if you want to reopen and continue the review

2022-07-29 11:41 UTC, closed without merging