Feat/sdk 3684
auth0/auth0-python pull request #448
Opened 2022-10-18 14:58 UTC by frederikprijck

### Changes

This PR moves the readme from using [`reStructuredText`](https://docutils.sourceforge.io/rst.html) to markdown, to make it easier to integrate our rebranded footer, as well as to align the readme with the other SDK, who all use markdown.

The navigation is added to the README.md file to ensure it also works on the generated documentation using `Sphinx` through `readthedocs`. The logo's are also added twice, once for the readme in github and once for the docs site.

Added an `EXAMPLES.md` file, and moved a couple of examples from the readme into that file.

It also configures `setuptools` to use markdown, to ensure our markdown is used when published to pypi.

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors

2022-10-18 14:59 UTC, frederikprijck commented on README.md
> +</div>
Needed to use HTML here, as well as actual emoji's rather than github's `:book:`, to ensure it renders as expected on our generated documentation.

2022-10-18 15:19 UTC, frederikprijck commented
Running the docs locally:

![image](https://user-images.githubusercontent.com/2146903/196472411-924e09ec-b1d7-4837-a875-6effe66bbde0.png)
![image](https://user-images.githubusercontent.com/2146903/196472494-33ded342-9818-42ed-9ebd-1f0fdc060275.png)

2022-10-25 09:55 UTC, ewanharris requested changes

2022-10-25 09:55 UTC, ewanharris commented on docs/source/conf.py
> +html_extra_path = ["../../auth0_dark_mode.png", "../../auth0_light_mode.png"]
Can remove these now we're using CDN
```suggestion
```

2022-10-25 10:11 UTC, merged